version: '3.4'
services:

  env.test:
    image: nginx:alpine
    container_name: demo-nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8881:8881"
      - "8443:443"
    volumes:
        - ./:/var/www
        - ./docker/config/nginx/conf.d/envtest.conf:/etc/nginx/conf.d/default.conf:ro

  demo-php-fpm:
    build:
      context: .
      dockerfile: ./docker/dockerfiles/php-fpm/Dockerfile
      target: develop
    image: davegthemighty/demo-php-fpm:latest
    container_name: demo-php-fpm
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/config/php/local.ini:/usr/local/etc/php/conf.d/local.ini

  demo-mysql:
    build:
      context: .
      dockerfile: ./docker/dockerfiles/mysql/Dockerfile
      target: develop
    image: davegthemighty/demo-mysql:latest
    container_name: demo-mysql
    restart: unless-stopped
    tty: true
    ports:
      - "4306:3306"
    volumes:
      - $PWD/docker/volumes/mysql:/var/lib/mysql
      - ./docker/config/mysql/my.cnf:/etc/mysql/my.cnf
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=demo_dev
      - MYSQL_USER=demo_usr
      - MYSQL_PASSWORD=demo_pw

