name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout step
      uses: actions/checkout@v2
    - name: Pull docker images
      run: |
        docker pull davegthemighty/demo-php-fpm:latest
        docker pull davegthemighty/demo-mysql:latest
    - name: Start Docker Containers
      run: | 
        docker-compose up -d
    - name: Composer step
      run: docker exec demo-php-fpm composer install  
    - name: Configure Site
      run: |
        chmod -R 777 storage
        cp .env.docker .env
        mkdir -m 777 coverage
        docker exec demo-php-fpm php artisan key:generate
    - name: Include Node
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Create Test Assets
      run: |
        npm install
        npm run dev
    - name: Wait for mysql 
      run: | 
        echo 'pausing: waiting for mysql to come available'
        ./docker/config/mysql/.wait-for-mysql.sh
        echo 'un-pausing: mysql is now available' 
    - name: Create Database
      run: |
        docker exec demo-php-fpm php artisan migrate:install
        docker exec demo-php-fpm php artisan migrate
        docker exec demo-php-fpm php artisan db:seed
    - name: PHP Test Step
      run: docker exec demo-php-fpm php artisan test --parallel
    - name: Jest Test Step
      if: ${{ always() }}
      run: npm run test
    - name: Run Dusk Tests
      if: ${{ success() }}
      run: |
        docker exec demo-php-fpm php artisan dusk
    - name: Create Production Assets
      if: ${{ success() }}
      run: |
        npm run prod
    - name: Check php unit test coverage
      id: test-php-coverage
      uses: johanvanhelden/gha-clover-test-coverage-check@v1
      with:
        percentage: "60"
        rounded-precision: 2
        exit: false
        filename: coverage/php/clover.xml
    - name: Add php coverage comment
      uses: mshick/add-pr-comment@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        message: |
          Coverage: ${{ steps.test-php-coverage.outputs.coverage }}
        allow-repeats: false
    - name: Check js test coverage
      id: test-js-coverage
      uses: johanvanhelden/gha-clover-test-coverage-check@v1
      with:
        percentage: "60"
        rounded-precision: 2
        exit: false
        filename: coverage/js/clover.xml
    - name: Add js coverage comment
      uses: mshick/add-pr-comment@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        message: |
          Javascript Coverage: ${{ steps.test-js-coverage.outputs.coverage }}
        allow-repeats: false
    - name: Upload Code Coverage
      uses: actions/upload-artifact@v2
      with:
        name: code coverage report
        path: coverage
    - name: Upload Assets
      if: ${{ success() }}
      uses: actions/upload-artifact@v2
      with:
        name: assets
        path: |
          public/css/app.css
          public/js/app.js
          public/js/app.js.LICENSE.txt
    - name: Upload Dusk Screenshots and Console
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: dusk
        path: |
          tests/Browser/screenshots
          tests/Browser/console
